application_hostname=a62defd9d69314c968a2b68821404ebd-640518803.us-east-2.elb.amazonaws.com
application_protocol=http
application_port=80
application_postfix=/jira
total_actions_per_hr=54500
perc_create_issue=3
perc_search_jql=10
perc_view_issue=13
perc_view_project_summary=2
perc_view_dashboard=9
perc_edit_issue=4
perc_add_comment=2
perc_browse_projects=8
perc_view_scrum_board=7
perc_view_kanban_board=6
perc_view_backlog=5
perc_browse_boards=1
perc_standalone_extension=30
